service: retailontap-backend

useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    useChildProcesses: true
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:SLS_STAGE}
  region: eu-west-2

functions:

  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          caching:
            enabled: false
  incoming:
    handler: stripe.default
    events:
      - http:
          path: stripe/incoming
          method: post